### ISSUE TITLE
Console log button notification number counting all logs, rather than just Errors

### ISSUE THREAD

**Issue by brknsoul** [BinaryQuantumSoul/sdnext-modernui#10]

**Comment by brknsoul** [comment]
Seemingly fixed.

**Comment by brknsoul** [comment]
Ok, not fixed, as soon as an error occurs (eg: an OOM error) the notification number starts counting all messages, instead of just errors, until the button is clicked, then it clears.

**Comment by vladmandic** [comment]
fixed internally, will post to dev soon.
