### ISSUE TITLE
[Feature] Clicking an already enabled aside tab should collapse aside tab pane

### ISSUE THREAD

**Issue by brknsoul** [BinaryQuantumSoul/sdnext-modernui#12]
When the aside tab pane is collapsed, clicking a tab uncollapses it. Clicking an enabled tab should also collapse it.

Use case example: Click Quicksettings > Select model > Click Quicksettings again to collapse, rather than having to click the collapse button at the bottom.

**Comment by BinaryQuantumSoul** [comment]
It makes sense, fearly easy to do with js

**Comment by BinaryQuantumSoul** [comment]
Done in latest eb139bd8911c62451e7f1dc62ad7772d87de900f
