### ISSUE TITLE
[Feature] Text/Image subtabs are horizontal, Control subtabs are vertical.

### ISSUE THREAD

**Issue by brknsoul** [BinaryQuantumSoul/sdnext-modernui#13]
Text and Image subtabs are shown horizontally;
![image](https://github.com/BinaryQuantumSoul/sdnext-modernui/assets/1969381/6743f2d1-c46d-492d-8b19-7817ca9979cc)

While the Control subtabs are shown vertically;
![image](https://github.com/BinaryQuantumSoul/sdnext-modernui/assets/1969381/e79ed22a-5a3e-4926-8816-fa1c03896dfa)

IMO: Horizontal is better, unless there's a plan to add more tabs.

**Comment by BinaryQuantumSoul** [comment]
it's because you can collapse control tabs

**Comment by vladmandic** [comment]
also you can think about it this way - unless you enable legacy iterface with text/image/control, its just control so its consistent since its the only one :)

**Comment by BinaryQuantumSoul** [comment]
Anyway control tab is unique also for its three columns and checkboxes
