### ISSUE TITLE
[Issue] Control > Base > Seed UI elements misaligned

### ISSUE THREAD

**Issue by brknsoul** [BinaryQuantumSoul/sdnext-modernui#14]
![image](https://github.com/BinaryQuantumSoul/sdnext-modernui/assets/1969381/a15c79ff-2d5e-4d9a-b04b-1eb72b2fc5ea)

**Comment by Disty0** [comment]
Fixed: https://github.com/BinaryQuantumSoul/sdnext-modernui/commit/70822967d57f89fc01304df4feb2b0e312047e17
