### ISSUE TITLE
[Feature] Control missing re-use seed button

### ISSUE THREAD

**Issue by brknsoul** [BinaryQuantumSoul/sdnext-modernui#15]

**Comment by Disty0** [comment]
Seems like this feature is missing in the backend.

**Comment by vladmandic** [comment]
reuse seed implementation dates from a1111 days and is really bad, it basically does a text parse of the status line string that ui placed in txt2img interface. i don't want to print random text in control tab just to be able to parse it later, this feature needs complete rewrite - and until that happens, its disabled in core.

**Comment by BinaryQuantumSoul** [comment]
Indeed it will need to be rewritten for control tab backend. Once it's done we can unhide it from modernui (it's already there but hidden)
