### ISSUE TITLE
[Issue] Extra Networks tab doesn't use entire height

### ISSUE THREAD

**Issue by brknsoul** [BinaryQuantumSoul/sdnext-modernui#16]
The Extra Networks tab doesn't use the entire height of the window, leaving some inaccessible Networks;

This image is scrolled all the way to the bottom, losing the scroll widget;

![image](https://github.com/BinaryQuantumSoul/sdnext-modernui/assets/1969381/5c6ce7f8-02d4-48e9-a7b1-8e395a0a018a)

**Comment by brknsoul** [comment]
Seems intermittent.. can't seem to figure out why this happens

**Comment by vladmandic** [comment]
root cause is because i have no idea how to set css to actually limit itself to available space and not overflow (yeah, obvious solutions don't work)

```
*.extra-network-cards {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
    grid-template-rows: max-content;
    width: 100%;
    height: calc(100vh - 168px);
    overflow-x: hidden;
    overflow-y: auto;
}
```
i've modified height from hard-coded 87vh to above, hope this helps, but any ideas are welcome.
in the meantime closing this as 'good enough'
