### ISSUE TITLE
[Issue] Control Tab zooms on the image by default

### ISSUE THREAD

**Issue by Disty0** [BinaryQuantumSoul/sdnext-modernui#18]
Default:
![image](https://github.com/BinaryQuantumSoul/sdnext-modernui/assets/47277141/99f2d11d-1ed5-4d15-a492-52278b516bda)

Have to click on the image to show the full image:

![image](https://github.com/BinaryQuantumSoul/sdnext-modernui/assets/47277141/25dd6ab3-640f-4093-8b71-71d2db23d947)

**Comment by vladmandic** [comment]
fixed.
