### ISSUE TITLE
[Issue] Generate buttons css

### ISSUE THREAD

**Issue by BinaryQuantumSoul** [BinaryQuantumSoul/sdnext-modernui#28]
The generate buttons don't all share the same css colors.
They should all use same colors as params buttons i.e. 
`--sd-input-text-color`: normal text
`--sd-input-hover-text-color`: hover/selected text
`--sd-input-background-color`: normal background
`--sd-main-accent-color`: hover/selected background

Error can be seen in `Vlad-Default` and `IlluZn-Superuser` themes
![image](https://github.com/BinaryQuantumSoul/sdnext-modernui/assets/19613657/01486c64-ea30-49b0-bb30-3fbf2851fe90)
![image](https://github.com/BinaryQuantumSoul/sdnext-modernui/assets/19613657/f36729b9-17c9-4b3c-a233-36961d156696)
![image](https://github.com/BinaryQuantumSoul/sdnext-modernui/assets/19613657/8e9edc92-c2b2-4844-b734-df07320d1e81)

Eventually we could make more intuitive variables that fall back to those by default which would be normal and hover/selected colors for text and background on all buttons inside params and generate

**Comment by vladmandic** [comment]
fixed.
