### ISSUE TITLE
[Issue]: Mouse / finger scrolling not working in the prompt input fields

### ISSUE THREAD

**Issue by lbeltrame** [BinaryQuantumSoul/sdnext-modernui#37]
### Issue Description

As the title says, the view doesn't scroll unless it is done via the cursor keys: mouse wheel and touch (on mobile) do not have any effect.

### Backend

Firefox

### Branch

Desktop

### Version Platform Description

Firefox 124, both on Linux and on mobile (Pixel 8)

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
fixed.
