### ISSUE TITLE
[Issue] "Play a notification upon completion" not functioning

### ISSUE THREAD

**Issue by brknsoul** [BinaryQuantumSoul/sdnext-modernui#39]
### Issue Description

The referenced mp3 file is not being played when generation is complete.

### Backend

Chrome (and derivatives)

### Branch

Desktop

### Version Platform Description

app: SD.next
updated: 2024-04-28
hash: 01e2ab05
url: https://github.com/vladmandic/automatic/tree/dev

### Relevant log output

```shell
n/a
```

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
fixed internally, will push update shortly.
