### ISSUE TITLE
[Issue] Log Entries Out-of-Order

### ISSUE THREAD

**Issue by brknsoul** [BinaryQuantumSoul/sdnext-modernui#40]
### Issue Description

Attached is a copypaste from the modernui log entries, they're out of order;
[chronfail.txt](https://github.com/BinaryQuantumSoul/sdnext-modernui/files/15172094/chronfail.txt)

### Backend

Chrome (and derivatives)

### Branch

Desktop

### Version Platform Description

app: SD.next
updated: 2024-04-30
hash: 070ae614
url: https://github.com/vladmandic/automatic/tree/dev

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
would be great if you could upload pair - server log and whats seen in the client at the same time.

**Comment by brknsoul** [comment]
It seems to happening while i'm scrolling the server log, it sort jumps all over the place when new entries are added

**Comment by vladmandic** [comment]
ok, that helps, i'll check

**Comment by vladmandic** [comment]
fixed internally, will post to dev soon.
