### ISSUE TITLE
[Issue] Gallery view when forced to column mode should autosize correctly

### ISSUE THREAD

**Issue by vladmandic** [BinaryQuantumSoul/sdnext-modernui#45]
### Issue Description

in side-by-side view if screen is wide enough everything looks fine.
but resizing browser window to force re-layout to column mode makes each column take too much space so there is a massive gap between input and output columns.

for example:
![image](https://github.com/BinaryQuantumSoul/sdnext-modernui/assets/57876960/5c2c02c3-a767-4ae1-8dce-857105720ca3)

when there is enough room, columns should be auto-sized to fit like this:
![image](https://github.com/BinaryQuantumSoul/sdnext-modernui/assets/57876960/a3bc0fd0-194e-42ea-b2b3-c73228322e33)

but i haven't been able to set css rules to work, 

### Backend

Chrome (and derivatives)

### Branch

Desktop

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
@BinaryQuantumSoul if you have any ideas, let me know. i'm guessing this is pretty much due to flex grow, but i cannot figure out what is it growing to.

**Comment by BinaryQuantumSoul** [comment]
I think it is the `aspect-ratio` css value on control columns children. I put it because when there were no images, it looked too narrow, but there may be different approaches

**Comment by vladmandic** [comment]
thats it! also needed to remove some width: 100% and replace with max-width so images would not blow up, but looking good now.
