### ISSUE TITLE
[Issue] dev/new ui: "Extra networks" columns broken

### ISSUE THREAD

**Issue by Tillerz** [BinaryQuantumSoul/sdnext-modernui#46]
### Issue Description

1. it seems the button to change the view mode (list vs name+image) isn't doing anything anymore.

2. The columns listing all the extra networks are too narrow. Resizing the window or using the divider to make the sidebar wider doesn't help, then you get MORE too narrow columns. Showing the info about one entry in 2 lines instead of 2 rows would already help a lot, so that you have (example LORAs) the name at the top, and then the keywords underneath, and the name is not broken into 2-4 character chunks each.

![image](https://github.com/vladmandic/automatic/assets/63370525/b220abfc-7662-4247-9e1f-2f8a0935e8e3)

### Backend

Chrome (and derivatives)

### Branch

Desktop

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
both items should be fixed now.
