### ISSUE TITLE
README.md large images

### ISSUE THREAD

**Issue by JetVarimax** [BinaryQuantumSoul/sdnext-modernui#52]
On my broadband connection, which is probably slow for today's standards, the README takes about 20 seconds to load and paint the almost 20MB of PNG screenshots. JPEG or similar would reduce the size considerably. Thumbnails could be good instead, but I am not sure if that is a feature of Github.
Regards,
Someone awaiting a fibre-optic internet connection!

**Comment by vladmandic** [comment]
I agree, will update screenshot.

**Comment by vladmandic** [comment]
fixed.
