### ISSUE TITLE
[Issue] Networks tabs: weird spacing issue at certain screen widths

### ISSUE THREAD

**Issue by Tillerz** [BinaryQuantumSoul/sdnext-modernui#53]
### Issue Description

When resizing the screen wth a Networks tab open (eg a sub folder with LORAs), at a certain size it leaves an empty row inbetween.

![image](https://github.com/BinaryQuantumSoul/sdnext-modernui/assets/63370525/d9b6b4d6-49e2-44b7-801f-bbc99f74a923)

### Backend

Chrome (and derivatives)

### Branch

Desktop

### Version Platform Description

49c997e WSL2, Win11

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by BinaryQuantumSoul** [comment]
Probably related to flexbox css and may have similar issue in the end of gallery tab

**Comment by vladmandic** [comment]
fixed for en.
