### ISSUE TITLE
Modified date on mouseover in gallery is incorrect

### ISSUE THREAD

**Issue by TigerFox57** [BinaryQuantumSoul/sdnext-modernui#57]
### Issue Description

In the gallery view, hovering over a thumbnail to show info has incorrect data for the modified date of the image. Even in the UK it's wrong :)

### Backend

Chrome (and derivatives)

### Branch

Desktop

### Version Platform Description

Windows 11, Chrome,   Version: app=sd.next updated=2024-05-29 hash=7a7cea3b branch=master url=https://github.com/vladmandic/automatic/tree/master
![Screenshot 2024-05-29 101650](https://github.com/BinaryQuantumSoul/sdnext-modernui/assets/113438851/9b38b0f1-0f2c-4a13-ae32-80914e23cf2c)

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
fixed.
