### ISSUE TITLE
[Issue] Right column Lora dirs \ Model dirs isn't scrollable

### ISSUE THREAD

**Issue by Razunter** [BinaryQuantumSoul/sdnext-modernui#58]
### Issue Description

Can't fit all dirs there and it isn't scrollable. Tried stable Firefox & Chrome.

![firefox](https://github.com/BinaryQuantumSoul/sdnext-modernui/assets/362900/f38aa842-286e-46e3-af3c-cf5263eb16d3)

### Backend

Firefox

### Branch

Desktop

### Relevant log output

```shell
14:22:02-717967 INFO     Python 3.10.11 on Windows
14:22:02-919437 INFO     Version: app=sd.next updated=2024-05-29 hash=7a7cea3b branch=master
                         url=https://github.com/vladmandic/automatic/tree/master
14:22:03-759113 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 151 Stepping 2, GenuineIntel system=Windows
                         release=Windows-10-10.0.22621-SP0 python=3.10.11
```

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
fixed.
