### ISSUE TITLE
[Feature] Theme-matching checkboxes and radio buttons

### ISSUE THREAD

**Issue by Mabi19** [BinaryQuantumSoul/sdnext-modernui#66]
### Feature description

In all the built-in themes, native UI elements (namely checkboxes and radio buttons) currently stay in light mode.
![default color-scheme](https://github.com/BinaryQuantumSoul/sdnext-modernui/assets/51255609/20bb780b-c164-41f8-9817-09db7591ea02)
(pictured: Eoan-Alpha)
However, I think that dark mode checkboxes and radio buttons would look better in dark themes, like this:
![with color-scheme: dark](https://github.com/BinaryQuantumSoul/sdnext-modernui/assets/51255609/8262f47e-afad-421e-bdd9-28514281a9b3)
This can be accomplished with a one-line CSS change (adding `color-scheme: dark` to `:root` in all the themes with dark backgrounds).

Since this is such a simple change, I could probably make a PR to add this myself.

### Version Platform Description

Using the version included with SDNext 84f9caa, on Windows 11.
I took the screenshots on Firefox 126, but changing color-scheme also works on Chromium-based browsers.

**Comment by BinaryQuantumSoul** [comment]
Interesting. Can be a temporary solution until we decide on a checkbox rework (if we want that). Would you mind PRing those ?

**Comment by Mabi19** [comment]
Sure! I'll get started on that soon.

**Comment by Mabi19** [comment]
PR is up, #69 (lol nice)

**Comment by BinaryQuantumSoul** [comment]
Thank you :)
