### ISSUE TITLE
Empty page... Nothing showing :(

### ISSUE THREAD

**Issue by RGX650** [BinaryQuantumSoul/sdnext-modernui#7]
Version: app=sd.next 
updated=2024-04-09 
hash=7ecc1d7d 
branch=master

[sdnext-ui-ux](https://github.com/BinaryQuantumSoul/sdnext-ui-ux) 9a60d6d3

webui-user.bat:
set COMMANDLINE_ARGS= --autolaunch --allow-code --debug --use-cuda --device-id 0 --use-xformers --upgrade --theme modern

It opens         http://127.0.0.1:7860/
instead of      http://127.0.0.1:7860/?__theme=modern

After the Loading animation i am left with an empty page...
Even when opening manually     http://127.0.0.1:7860/?__theme=modern

same behaviour for
git checkout 951653d
git checkout cb9de04

**Comment by 1NFERR** [comment]
Same problem

**Comment by Disty0** [comment]
`branch=master`

This only works in dev branch right now.  
Wait for the proper release if you want to use this in master branch.
