### ISSUE TITLE
[Issue] Prompt fields collapsed on high zoom (150%+)

### ISSUE THREAD

**Issue by PurplefinNeptuna** [BinaryQuantumSoul/sdnext-modernui#72]
### Issue Description

Above 100% zoom, prompt fields got small and smaller until it fully collapsed at 150% (1080p monitor)
![image](https://github.com/BinaryQuantumSoul/sdnext-modernui/assets/23467102/9796c468-2875-4f21-8bc7-a13b4e465e48)
### How to replicate
Zoom In (CTRL+Scroll Up)

### Backend

Chrome (and derivatives)

### Branch

Desktop

### Version Platform Description

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by BinaryQuantumSoul** [comment]
Related to https://github.com/BinaryQuantumSoul/sdnext-modernui/issues/50

**Comment by BinaryQuantumSoul** [comment]
Fixed
