### ISSUE TITLE
[Issue] No Override Settings Field 

### ISSUE THREAD

**Issue by xedis** [BinaryQuantumSoul/sdnext-modernui#78]
### Issue Description

![image](https://github.com/user-attachments/assets/d24416a7-c83d-443c-9e26-1602dbd6473d)

Just expose it please, don't care where just....bring it back. Causing all sorts of issues not being able to clear those values when they exist. I can provide logs if really needed but this should theorectically be an easy fix.

Steps to recreate:

1. View an existing image that exists on a different part of the webui. 
2. Send to txt2img or img2img or control even.
3. Override values will show in the console log but not be reflected in the UI. 

### Backend

Chrome (and derivatives)

### Branch

Desktop

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
added.
