### ISSUE TITLE
To Text and To Image buttons in gallery

### ISSUE THREAD

**Issue by Aptronymist** [BinaryQuantumSoul/sdnext-modernui#8]
At present they send the user to a page for each that cannot be reached any other way.

**Comment by BinaryQuantumSoul** [comment]
Fix is to add `only-legacy` to their classList, the same way `only-diffusers` is on send to control button

**Comment by Aptronymist** [comment]
Yeah, this was before I knew an option had been added to hide/show them, disregard.

**Comment by BinaryQuantumSoul** [comment]
I still need to fix the templates though to not show the sendto buttons.

**Comment by BinaryQuantumSoul** [comment]
Done
