### ISSUE TITLE
[Issue] Extra Networks tab is cut off

### ISSUE THREAD

**Issue by InternIsla** [BinaryQuantumSoul/sdnext-modernui#80]
### Issue Description

As in #16, when using ModernUI, the Extra Networks tab doesn't use the full height of the UI, which makes some elements inside the tab unusable. (In this screenshot, there are ~3 models that aren't visible and can't be selected in the UI)

![image](https://github.com/user-attachments/assets/d242fde7-8e3a-4ad8-b4ad-b91cc1e3c875)

### Backend

Firefox

### Branch

Desktop

### Version Platform Description

Tested with current SD.Next version from master branch
Tested on Windows and Linux
Tested with Floorp (Firefox derivative) and Edge (Chrome derivative)

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
fixed in latest dev branch.
